export const projectsList = [
  {
    name: "Color flipper",
    description: "Press the button to change the background color.",
    thumbnail: "./img/projects_image/color_fliper_300x300.png",
    githubLink: "https://github.com/MenagoChicken/Color-Flipper",
    pageUrl: "./projects/color-flipper/",
    difficulty: 1,
  },
  {
    name: "Counter",
    description: "Counter with usage of local storage.",
    thumbnail: "./img/projects_image/counter_300x300.png",
    githubLink: "https://github.com/MenagoChicken/Counter",
    pageUrl: "./projects/counter",
    difficulty: 1,
  },
  {
    name: "Guess the number - MDN",
    description: "Guess the number game.",
    thumbnail: "./img/projects_image/guess_the_number_300x300.png",
    githubLink:
      "https://github.com/MenagoChicken/small-projects/tree/main/guess-the-number",
    pageUrl: "./projects/small-projects/guess-the-number",
    difficulty: 1,
  },
  {
    name: "Image gallery",
    description: "Image galery based on a grid.",
    thumbnail: "./img/projects_image/image_gallery_300x300.png",
    githubLink: "https://github.com/MenagoChicken/image-gallery",
    pageUrl: "./projects/image-gallery",
    difficulty: 2,
  },
  {
    name: "Pokedex",
    description: "Pokedex using API. Search bar inside.",
    thumbnail: "./img/projects_image/pokedex_300x300.png",
    githubLink: "https://github.com/MenagoChicken/Pokedex",
    pageUrl: "./projects/pokedex",
    difficulty: 5,
  },
  {
    name: "Word counter",
    description: "Count words, letters and characters.",
    thumbnail: "./img/projects_image/word_counter_300x300.png",
    githubLink:
      "https://github.com/MenagoChicken/small-projects/tree/main/how-many-words",
    pageUrl: "./projects/small-projects/how-many-words",
    difficulty: 2,
  },
  {
    name: "Todo",
    description: "Make a todo list.",
    thumbnail: "./img/projects_image/todo_300x300.png",
    githubLink: "https://github.com/MenagoChicken/todo",
    pageUrl: "./projects/todo",
    difficulty: 4,
  },
];
